### ISSUE TITLE
hello, I have a question about AD metric

### ISSUE THREAD

**Issue by hanquansanren** [cvlab-stonybrook/PaperEdge#11]
Hello ke,
in eval directory in your repo, I have seen a parameter as follow:
https://github.com/cvlab-stonybrook/PaperEdge/blob/8f917387b69c309b3e5b847958edffac8eace1bc/eval/run_benchmark.m#L10

Based on my understanding, it's a parameter to control the resize ratio, but I don't know why to use `598400`, can you help me?

Best wishes,
Weiguang Zhang

**Comment by wkema** [comment]
It is the total area (num of pixels) for each image.

I have been using this number since the first paper:
https://www3.cs.stonybrook.edu/~cvl/content/papers/2018/Ma_CVPR18.pdf
(see the experiment setup section)

Well, the reason is more or less heuristic and empirical lol. I think I calculated it as:
The size of US letters is `8.5*11` inch and the web image ppi (or the screen ppi) is 72. I bumped 72 to 80 thus the total number of pixels of a US letter size document under the screen ppi is `8.5*11*80*80=598400`.

It would be great if you could further investigate the influence of the area size in the metrics.

Hope this helps.

**Comment by hanquansanren** [comment]
Hello Ke,
Many thanks for your kind response which help me a lot.
